name: hp_dnn
channels:
  - pytorch
  - defaults
  - conda-forge
  - nvidia
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=2.0.0
  - blessed=1.19.0
  - ca-certificates=2025.7.14
  - certifi=2021.5.30
  - cffi=1.14.4
  - colorama=0.4.5
  - conda-pack=0.7.0
  - cudatoolkit=11.7.0
  - cudnn=8.2.1.32
  - cycler=0.11.0
  - dataclasses=0.8
  - dbus=1.13.6
  - decorator=5.1.1
  - entrypoints=0.4
  - expat=2.7.0
  - fontconfig=2.14.0
  - freetype=2.10.4
  - future=0.18.2
  - gettext=0.23.1
  - gettext-tools=0.23.1
  - glib=2.66.3
  - gpustat=1.1.1
  - gst-plugins-base=1.14.5
  - gstreamer=1.14.5
  - icu=67.1
  - ignite=0.5.1
  - intel-openmp=2021.4.0
  - ipykernel=5.5.5
  - ipython=7.16.1
  - ipython_genutils=0.2.0
  - jbig=2.1
  - jedi=0.17.2
  - jpeg=9e
  - jupyter_client=7.1.2
  - jupyter_core=4.8.1
  - kiwisolver=1.3.1
  - krb5=1.20.1
  - lcms2=2.12
  - lerc=2.2.1
  - libasprintf=0.23.1
  - libasprintf-devel=0.23.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=10.0.1
  - libdeflate=1.7
  - libedit=3.1.20230828
  - libevent=2.1.10
  - libexpat=2.7.0
  - libffi=3.2.1
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgettextpo=0.23.1
  - libgettextpo-devel=0.23.1
  - libglib=2.66.3
  - libgomp=14.2.0
  - libiconv=1.18
  - liblapack=3.9.0
  - libllvm10=10.0.1
  - liblzma=5.6.4
  - liblzma-devel=5.6.4
  - libpng=1.6.37
  - libpq=12.15
  - libprotobuf=3.18.0
  - libsodium=1.0.18
  - libstdcxx=14.2.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.3.0
  - libuuid=2.38.1
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxkbcommon=0.10.0
  - libxml2=2.9.10
  - libzlib=1.2.13
  - lz4-c=1.9.3
  - magma=2.5.4
  - matplotlib=3.3.4
  - matplotlib-base=3.3.4
  - mkl=2021.4.0
  - mysql-common=8.0.25
  - mysql-libs=8.0.25
  - nccl=2.12.12.1
  - ncurses=6.4.20240210
  - nest-asyncio=1.6.0
  - ninja=1.11.0
  - nspr=4.36
  - nss=3.59
  - numpy=1.19.5
  - nvidia-ml-py=12.560.30
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1w
  - packaging=21.3
  - pandas=1.1.5
  - parso=0.7.1
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.3.2
  - pip=21.2.2
  - prompt-toolkit=3.0.36
  - protobuf=3.18.0
  - psutil=5.8.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pycparser=2.21
  - pygments=2.14.0
  - pyparsing=3.1.4
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - python=3.6.9
  - python-dateutil=2.8.2
  - python_abi=3.6
  - pytorch=1.9.1
  - pytorch-gpu=1.9.1
  - pytz=2023.3.post1
  - pyzmq=22.3.0
  - qt=5.12.9
  - readline=7.0
  - setuptools=58.0.4
  - six=1.16.0
  - sleef=3.8
  - sqlite=3.33.0
  - tensorboardx=2.5.1
  - tk=8.6.14
  - torchvision=0.10.1
  - tornado=6.1
  - tqdm=4.65.0
  - traitlets=4.3.3
  - typing_extensions=4.1.1
  - wcwidth=0.2.10
  - wheel=0.37.1
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.6.4
  - xz-gpl-tools=5.6.4
  - xz-tools=5.6.4
  - zeromq=4.3.4
  - zlib=1.2.13
  - zstd=1.5.0
prefix: /home/farzin/anaconda3/envs/hp_dnn
